run:
    timeout: 10m
    skip-files:
        - ".*\\.pb\\.go$"

    modules-download-mode: vendor
    allow-parallel-runners: true
    # build-tags:

linters:
    enable:
        - gofmt
        - govet
        - depguard
        - goimports
        - misspell
        - unused
        - revive
        - staticcheck
        - typecheck
        - nolintlint
        - gosec
        - forbidigo
        - bodyclose
        - depguard
        - errcheck
        # - goconst
        - gofmt
        - goimports
        - gosimple
        - govet
        - ineffassign
        - misspell
        - nakedret
        - prealloc
        - revive
        - staticcheck
        - stylecheck
        - typecheck
        - unconvert
        - unparam
        - unused
        - zerologlint
    disable-all: true

linters-settings:
    depguard:
        rules:
            include-go-root: {}
            pacakges: { deny: [{ pkg: "io/ioutil" }] }
    forbidigo:
        forbid:
            - '^fmt\.Errorf(# use errors\.Errorf instead)?$'
            - '"github.com/pkg/errors"(# use errors or "github.com/go-faster/errors")?$'
    gosec:
        excludes:
            - G204 # Audit use of command execution
            - G402 # TLS MinVersion too low
        config:
            G306: "0644"

issues:
    exclude-rules:
        - linters:
              - revive
          text: "stutters"
        - linters:
              - revive
          text: "underscore in package name"
        - linters:
              - stylecheck
          text: "underscores in package name"

presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
