inpackage: False
with-expecter: True
testonly: False
keeptree: True
exported: True
dir: "{{.InterfaceDirRelative}}/mocks"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}mocks"
packages:
    {
        github.com/nuggxyz/buildrc/internal/provider:
            { interfaces: { Identifiable: {} } },
    }
case: underscore
