{
    inpackage: false,
    with-expecter: true,
    testonly: false,
    exported: true,
    outpkg: mockery,
    filename: "{{.InterfaceName}}.{{.PackageName}}.mockery.go",
    packages:
        {
            github.com/walteh/buildrc/internal/git:
                {
                    interfaces:
                        {
                            GitProvider:
                                { config: { mockname: "MockGitProvider" } },
                            ReleaseProvider:
                                {
                                    config:
                                        { mockname: "MockGitReleaseProvider" },
                                },
                            PullRequestProvider:
                                {
                                    config:
                                        {
                                            mockname: "MockGitPullRequestProvider",
                                        },
                                },
                        },
                },
        },
}
