inpackage: False
with-expecter: True
testonly: False
keeptree: True
exported: True
dir: "{{.InterfaceDirRelative}}/mocks/{{.PackageName}}mocks"
mockname: "{{.InterfaceName}}"
outpkg: "{{.PackageName}}mocks"
packages: {}
case: underscore
