name: Workflow 1
"on":
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    defaults: {}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
