// Code generated by mockery v2.29.0. DO NOT EDIT.

package climocks

import mock "github.com/stretchr/testify/mock"

// MockIdentifiable is an autogenerated mock type for the Identifiable type
type MockIdentifiable struct {
	mock.Mock
}

type MockIdentifiable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdentifiable) EXPECT() *MockIdentifiable_Expecter {
	return &MockIdentifiable_Expecter{mock: &_m.Mock}
}

// ID provides a mock function with given fields:
func (_m *MockIdentifiable) ID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockIdentifiable_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockIdentifiable_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockIdentifiable_Expecter) ID() *MockIdentifiable_ID_Call {
	return &MockIdentifiable_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockIdentifiable_ID_Call) Run(run func()) *MockIdentifiable_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIdentifiable_ID_Call) Return(_a0 string) *MockIdentifiable_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIdentifiable_ID_Call) RunAndReturn(run func() string) *MockIdentifiable_ID_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockIdentifiable interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockIdentifiable creates a new instance of MockIdentifiable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockIdentifiable(t mockConstructorTestingTNewMockIdentifiable) *MockIdentifiable {
	mock := &MockIdentifiable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
