{
    name: release,
    on: { push: { branches: ["*"] } },
    permissions:
        {
            id-token: write,
            contents: write,
            packages: write,
            actions: write,
            deployments: write,
            pull-requests: write,
            issues: write,
            statuses: write,
            checks: write,
        },
    env: { GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}" },
    jobs:
        {
            override:
                {
                    runs-on: ubuntu-latest,
                    steps:
                        [
                            {
                                uses: actions/checkout@v3,
                                with: { fetch-depth: 0 },
                            },
                            { id: setup-go, uses: actions/setup-go@v4 },
                            { id: download-go-deps, run: go mod download },
                            {
                                id: build-linux-amd64,
                                env: { GO_LDFLAGS: "-X main.Temporary=true" },
                                run: "${{ github.workspace }}/build.sh ${{ env.BUILDRC_EXEC_OVERRIDE }}",
                            },
                            {
                                id: setup-buildrc1,
                                uses: walteh/actions/setup-buildrc@main,
                            },
                            { id: build, run: "buildrc release build " },
                        ],
                },
            buildrc:
                {
                    uses: "walteh/actions/.github/workflows/reusable-buildrc-main.yaml@main",
                    secrets: inherit,
                    needs: [override],
                    concurrency: { group: release },
                    permissions:
                        {
                            contents: write,
                            packages: write,
                            id-token: write,
                            actions: write,
                            deployments: write,
                            pull-requests: write,
                            issues: write,
                            statuses: write,
                            checks: write,
                        },
                },
        },
}
