{
    name: release,
    on:
        {
            push: { branches: ["*"] },
            pull_request: { types: [ready_for_review, converted_to_draft] },
        },
    permissions:
        {
            id-token: write,
            contents: write,
            packages: write,
            actions: write,
            deployments: write,
            pull-requests: write,
            issues: write,
            statuses: write,
            checks: write,
        },
    env: { GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}" },
    jobs:
        {
            override:
                {
                    runs-on: ubuntu-latest,
                    steps:
                        [
                            { uses: actions/checkout@v3 },
                            { id: setup-go, uses: actions/setup-go@v4 },
                            { id: download-go-deps, run: go mod download },
                            {
                                id: build-linux-amd64,
                                env:
                                    { GO_LDFLAGS: "-X version.Temporary=true" },
                                run: "${{ github.workspace }}/build.sh ${{ env.BUILDRC_EXEC_OVERRIDE }}",
                            },
                            {
                                id: setup-buildrc1,
                                uses: nuggxyz/actions/setup-buildrc@main,
                            },
                            { id: build, run: "buildrc release build " },
                        ],
                },
            setup:
                {
                    runs-on: ubuntu-latest,
                    needs: [override],
                    outputs:
                        {
                            BUILDRC_LOAD_PACKAGE_NAMES_ARRAY: "${{ env.BUILDRC_LOAD_PACKAGE_NAMES_ARRAY }}",
                            BUILDRC_SETUP_TAG: "${{ env.BUILDRC_SETUP_TAG }}",
                        },
                    steps:
                        [
                            { uses: actions/checkout@v3 },
                            {
                                id: setup-buildrc,
                                uses: nuggxyz/actions/setup-buildrc@main,
                            },
                            { id: setup-release, run: "buildrc release setup" },
                        ],
                },
            build:
                {
                    runs-on: ubuntu-latest,
                    needs: [setup],
                    strategy:
                        {
                            matrix:
                                {
                                    package: "${{ fromJson(needs.setup.outputs.BUILDRC_LOAD_PACKAGE_NAMES_ARRAY) }}",
                                },
                        },
                    steps:
                        [
                            { uses: actions/checkout@v3 },
                            {
                                id: setup-buildrc,
                                uses: nuggxyz/actions/setup-buildrc@main,
                            },
                            {
                                id: package,
                                run: "buildrc package ${{ matrix.package }}",
                            },
                            {
                                id: setup-go,
                                if: "${{ env.BUILDRC_PACKAGE_USES_GO == '1' }}",
                                uses: actions/setup-go@v4,
                            },
                            { id: build, run: "buildrc release build" },
                            { id: upload, run: "buildrc release upload" },
                        ],
                },
            test:
                {
                    runs-on: [ubuntu-latest],
                    needs: [setup, build],
                    steps:
                        [
                            {
                                id: test-latest-release,
                                uses: nuggxyz/actions/setup-buildrc@main,
                                with:
                                    {
                                        version: "${{ needs.setup.outputs.BUILDRC_SETUP_TAG }}",
                                    },
                            },
                        ],
                },

            docker:
                {
                    runs-on: ubuntu-latest,
                    needs: [test, setup],
                    strategy:
                        {
                            matrix:
                                {
                                    package: "${{ fromJson(needs.setup.outputs.BUILDRC_LOAD_PACKAGE_NAMES_ARRAY) }}",
                                },
                        },
                    steps:
                        [
                            { uses: actions/checkout@v3 },
                            {
                                id: setup-buildrc,
                                uses: nuggxyz/actions/setup-buildrc@main,
                            },
                            {
                                id: container,
                                run: "buildrc release container '${{ matrix.package }}'",
                            },
                            {
                                id: helper,
                                uses: nuggxyz/actions/buildrc-docker-helper@main,
                            },
                        ],
                },

            finalize:
                {
                    runs-on: ubuntu-latest,
                    needs: [docker],
                    steps:
                        [
                            { uses: actions/checkout@v3 },
                            {
                                id: setup-buildrc,
                                uses: nuggxyz/actions/setup-buildrc@main,
                            },
                            {
                                id: pre-release,
                                run: "buildrc release finalize",
                            },
                        ],
                },
        },
}
