{
    name: release,
    on: { push: { branches: ["*"] } },
    permissions:
        {
            id-token: write,
            contents: write,
            packages: write,
            actions: write,
            deployments: write,
            pull-requests: write,
            issues: write,
            statuses: write,
            checks: write,
        },
    env: { GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}" },
    jobs:
        {
            setup:
                {
                    runs-on: ubuntu-latest,
                    outputs:
                        {
                            BUILDRC_LOAD_PACKAGE_NAMES_ARRAY: "${{ env.BUILDRC_LOAD_PACKAGE_NAMES_ARRAY }}",
                        },
                    steps: [
                            { uses: actions/checkout@v3 },
                            { id: setup-go, uses: actions/setup-go@v4 },
                            { id: download-go-deps, run: go mod download },
                            {
                                id: build-linux-amd64,
                                run: "${{ github.workspace }}/build.sh linux amd64 ./build/linux-amd64",
                            },
                            {
                                id: artifact,
                                uses: actions/upload-artifact@v3,
                                with:
                                    {
                                        name: buildrc-override,
                                        path: "${{ github.workspace }}/build/linux-amd64",
                                    },
                            },
                            {
                                id: setup-buildrc,
                                uses: nuggxyz/actions/setup-buildrc@0.0.9,
                            },
                            # { id: next-tag, run: "buildrc tag next" },
                            # if we just build one, then the cache will never have the other build artifacts
                            # by building here we significantly decrease the build of the overall pipeline
                            # of course, if no cache, the build will have to run its coarse
                            # { id: build-all, run: "buildrc build" },
                        ],
                },
            build:
                {
                    runs-on: ubuntu-latest,
                    needs: [setup],
                    strategy:
                        {
                            matrix:
                                {
                                    package: "${{ fromJson(needs.setup.outputs.BUILDRC_LOAD_PACKAGE_NAMES_ARRAY) }}",
                                },
                        },
                    steps:
                        [
                            { uses: actions/checkout@v3 },
                            {
                                id: setup-buildrc,
                                uses: nuggxyz/actions/setup-buildrc@main,
                            },
                            {
                                id: load-package,
                                run: "buildrc package ${{ matrix.package }}",
                            },
                            {
                                id: setup-go,
                                if: "${{env.BUILDRC_PACKAGE_USES_GO == '1'}}",
                                uses: actions/setup-go@v4,
                            },
                            { id: pre-build, run: "buildrc build" },
                            { id: next-tag, run: "buildrc tag next" },
                        ],
                },
        },
}
