{
    name: release,
    on: { push: { branches: [main] } },
    permissions:
        { id-token: write, contents: write, packages: write, actions: write },
    env: { GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}" },
    jobs:
        {
            setup:
                {
                    runs-on: ubuntu-latest,
                    steps:
                        [
                            { uses: actions/checkout@v3 },
                            { id: setup-go, uses: actions/setup-go@v4 },
                            { id: download-go-deps, run: go mod download },
                            {
                                id: setup-buildrc11,
                                uses: nuggxyz/actions/setup-buildrc@main,
                            },
                            {
                                id: build,
                                run: "${{ github.workspace }}/prebuild.sh cmd linux amd64",
                            },
                            {
                                id: artifact,
                                uses: actions/upload-artifact@v3,
                                with:
                                    {
                                        name: buildrc-override,
                                        path: "${{ github.workspace }}/build/linux-amd64",
                                    },
                            },
                            {
                                id: setup-buildrc,
                                uses: nuggxyz/actions/setup-buildrc@main,
                            },
                            { id: next-tag, run: "buildrc tag next" },
                            { id: pre-build, run: "buildrc hook prebuild" },
                        ],
                },
            finish:
                {
                    runs-on: ubuntu-latest,
                    needs: [setup],
                    steps:
                        [
                            { uses: actions/checkout@v3 },
                            { id: setup-go, uses: actions/setup-go@v4 },
                            {
                                id: setup-buildrc,
                                uses: nuggxyz/actions/setup-buildrc@main,
                            },
                            { id: next-tag, run: "buildrc tag next" },
                            { id: pre-build, run: "buildrc hook prebuild" },
                            {
                                name: Create GitHub Release,
                                uses: ncipollo/release-action@v1,
                                with:
                                    {
                                        artifacts: "${{ env.BUILDRC_LOAD_ARTIFACTS }}",
                                        tag: "v${{ env.BUILDRC_TAG_NEXT_FULL }}",
                                        name: "${{ env.BUILDRC_TAG_NEXT_FULL }}",
                                        body: "Auto-generated release for ${{ env.BUILDRC_TAG_NEXT_FULL }}",
                                        draft: false,
                                        prerelease: "${{ github.ref != 'refs/heads/main' }}",
                                        commit: "${{ github.sha }}",
                                        allowUpdates: true,
                                    },
                            },
                        ],
                },
        },
}
